version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - micro-net

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: productservice
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - micro-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - micro-net

  authservice:
    build: 
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: authservice
    depends_on:
      - rabbitmq
      - sqlserver
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"

      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__User: guest
      RabbitMQ__Pass: guest

      Redis__Host: redis
      Redis__Port: 6379
    ports:
      - "8081:8081"
    networks:
      - micro-net

  productservice:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    container_name: productservice
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      DB_PROVIDER: mongo
      MONGO_URI: "mongodb://root:rootpass@mongodb:27017/productservice?authSource=admin"
      PORT: 8082
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8082:8082"
    networks:
      - micro-net
    volumes:
      - ./uploads/bouquets:/app/uploads/bouquets
      - ./data:/app/data   

  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: orderservice
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      PORT: 8083
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8083:8083"
    networks:
      - micro-net

  paymentservice:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    container_name: paymentservice
    depends_on:
      - rabbitmq
    environment:
      PORT: 8084
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8084:8084"
    networks:
      - micro-net
  couponservice:
    build:
      context: ./CouponService
      dockerfile: Dockerfile
    container_name: couponservice
    depends_on:
      - rabbitmq
    environment:
      PORT: 8086
    ports:
      - "8086:8086"
    networks:
      - micro-net
  notificationservice:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notificationservice
    depends_on:
      - rabbitmq
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"

      # RabbitMQ__Host: rabbitmq
      # RabbitMQ__Port: 5672
      # RabbitMQ__User: guest
      # RabbitMQ__Pass: guest

      # Redis__Host: redis
      # Redis__Port: 6379
    ports:
      - "8087:8087"
    networks:
      - micro-net
   
  apigateway:
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
    container_name: apigateway
    depends_on:
      - authservice
      - productservice
      - orderservice
      - paymentservice
    ports:
      - "8080:8080"
    networks:
      - micro-net
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    volumes:
      - ./APIGateway/src/ocelot.json:/app/ocelot.json  


networks:
  micro-net:
    driver: bridge

volumes:
  sql_data:
  mongo_data:
